# Change these first
owner: Jeremy Pratt # Your GitHub organization or username, where this repository lives
repo: upptimeHM # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptimeHM
  logoUrl: https://www.genetec.com/binaries/content/gallery/genetecweb/graphic-assets/logos/cs-logo-builder-thumbnail-homemakers-furniture_650x366px.jpg/cs-logo-builder-thumbnail-homemakers-furniture_650x366px.jpg/genetecweb%3Asmall
  name: Upptime
  introTitle: "Homemakers Server status"
  introMessage: This site shows the current status of the internal/external sites and their descriptions that HM uses.
  navbar:
    - title: Status
      href: /
    - title: Homemakers
      href: https://homemakers.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
